# Generated by Django 5.0.3 on 2024-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='role_permissions', to='permissions.permission'),
        ),
    ]
