# Generated by Django 5.0.3 on 2024-09-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0008_remove_department_dept_have_roles'),
        ('permissions', '0005_permission_module_name_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_has_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_role', to='hrm_app.department'),
        ),
    ]
