# Generated by Django 5.0.3 on 2024-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='employee_images/'),
        ),
    ]
