# Generated by Django 5.0.3 on 2024-09-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0003_payroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
