# Generated by Django 5.0.3 on 2024-09-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0005_alter_salary_employee_has_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
