# Generated by Django 5.0.3 on 2024-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0006_payroll_bonuses_payroll_overtime'),
        ('permissions', '0005_permission_module_name_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_have_roles',
            field=models.ManyToManyField(related_name='roles_of_dept', to='permissions.role'),
        ),
    ]
